// Generated by CoffeeScript 1.7.1
(function() {
  window.welcome = function() {
    return alert("hello");
  };

  String.prototype.capitalize = function() {
    var str;
    str = this;
    return str = str.toLowerCase().replace(/^[a-z]{1}/, function(letter) {
      return letter.toUpperCase();
    });
  };

  $(function() {
    return $('a.shit').starJones();
  });

}).call(this);
